name = "webhook-notification"
main = "src/index.js"
compatibility_date = "2022-12-18"
logpush = true

kv_namespaces = [
    { binding = "notification_namespace", id = "709ce8dbdd5945cc9fc538c7c19d8754" }
]

[triggers]
# crons = [ "*/5 * * * *" ]
crons = [ "35 1 * * 2-6", "40 1 * * 1" ]
# crons = [ "10 2 * * mon-fri" ]

[vars]
KV_STANDUP_OWNER_NAMES = "standup_owner_names"
MESSAGE_TYPE = "WeworkChat"
# MESSAGE_TYPE = "GoogleChat"
WEWORK_CHAT_WEBHOOK = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=54c781e4-8fba-417b-898e-a94b0d9ce1e9"
